apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-rambo-{{ .Values.part }}
  name: {{ .Release.Name }}-rambo-{{ .Values.part }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rambo-{{ .Values.part }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rambo-{{ .Values.part }}
    spec:
      containers:
      - image: bletvaska/rambo:{{ .Values.part | default 1 }}
        name: {{ .Release.Name }}-rambo-{{ .Values.part }}
