apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-rambo-{{ .Values.part | default 1 }}
  name: {{ .Release.Name }}-rambo-{{ .Values.part | default 1}}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-rambo-{{ .Values.part | default 1 }}
