apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo
  name: rambo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo
  template:
    metadata:
      labels:
        app: rambo
    spec:
      containers:
      - image: bletvaska/rambo:1
        name: rambo
